name: arcade_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.4=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - importlib-metadata=8.4.0=pyha770c72_0
  - importlib_metadata=8.4.0=hd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.26.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311h38be061_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=14.1.0=h77fa898_0
  - libgomp=14.1.0=h77fa898_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.3.1=hb9d3cd8_3
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=py311h06a4308_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=6.0.0=py311h331c9d8_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.11.9=h955ad1f_0
  - python_abi=3.11=2_cp311
  - pyzmq=25.1.2=py311h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py311h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.1=py311h331c9d8_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.20.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - certifi==2024.7.4
      - cffi==1.17.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - efficientnet-pytorch==0.7.1
      - fastjsonschema==2.20.0
      - filelock==3.13.1
      - fonttools==4.53.1
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.24.6
      - idna==3.8
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jinja2==3.1.3
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.5
      - lightning-utilities==0.11.6
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mistune==3.0.2
      - mpmath==1.3.0
      - multidict==6.0.5
      - munch==4.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - networkx==3.2.1
      - notebook==7.2.1
      - notebook-shim==0.2.4
      - numpy==2.1.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.10.0.84
      - overrides==7.7.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - pillow==10.4.0
      - pretrainedmodels==0.7.4
      - prometheus-client==0.20.0
      - protobuf==5.27.3
      - pycparser==2.22
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytorch-lightning==2.4.0
      - pytz==2024.1
      - pyyaml==6.0.2
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - referencing==0.35.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.0
      - safetensors==0.4.4
      - seaborn==0.13.2
      - segmentation-models-pytorch==0.3.4
      - send2trash==1.8.3
      - sentry-sdk==2.13.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.6
      - sympy==1.12
      - terminado==0.18.1
      - timm==0.9.7
      - tinycss2==1.3.0
      - torch==2.4.0+cu121
      - torchmetrics==1.4.1
      - torchvision==0.19.0+cu121
      - tqdm==4.66.5
      - triton==3.0.0
      - types-python-dateutil==2.9.0.20240821
      - typing-extensions==4.9.0
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==2.2.2
      - wandb==0.17.7
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.13
      - yarl==1.9.4